version: 2
updates:
- package-ecosystem: npm
  directory: "/front"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.25
    - 14.14.27
    - 14.14.28
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.36
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: "@types/react"
    versions:
    - 17.0.0
    - 17.0.1
    - 17.0.2
    - 17.0.3
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: react
    versions:
    - 16.14.0
- package-ecosystem: npm
  directory: "/api"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.25
    - 14.14.27
    - 14.14.28
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.36
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: pm2
    versions:
    - 4.5.2
    - 4.5.4
    - 4.5.5
